{-# LANGUAGE RoleAnnotations #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}

-- | Iso-recursive fixed points of operators on stable-confederal data.
--
-- A fixed point stores exactly one operator layer.  The operator interpreter
-- ties the guarded knot at the 'StableConfederalData' level; 'rollFixedPoint'
-- and 'unrollFixedPoint' witness the resulting recursive equation.
module FixedPoint
  ( FixedPoint
  , FixedPointValue
  , fixedPoint
  , fixedPointLayer
  , rollFixedPoint
  , unrollFixedPoint
  , rollFixedPointValue
  , unrollFixedPointValue
  , withFixedPointValue
  ) where

import Data.Kind (Type)
import StableConfederalData
  ( StableConfederalData
  , StableConfederalDataHom
  , StableConfederalDataValue
  , mapStableConfederalData
  , stableConfederalData
  , stableConfederalDataComposition
  , stableConfederalDataHom
  , stableConfederalDataIdentity
  )

-- | The nominal fixed point of an operator.  The tag keeps independently
-- named domain concepts distinct even when they use the same operator.
data FixedPoint tag (operator :: Type -> Type)

type role FixedPoint nominal nominal

-- | One observable operator layer of a fixed-point value.
type role FixedPointValue nominal nominal nominal
newtype FixedPointValue tag operator object = FixedPointValue
  (StableConfederalDataValue
    (operator (FixedPoint tag operator))
    object)

type instance
  StableConfederalDataValue (FixedPoint tag operator) object =
    FixedPointValue tag operator object

-- | Introduce one operator layer.
rollFixedPointValue
  :: StableConfederalDataValue
       (operator (FixedPoint tag operator))
       object
  -> FixedPointValue tag operator object
rollFixedPointValue = FixedPointValue

-- | Observe one operator layer.
unrollFixedPointValue
  :: FixedPointValue tag operator object
  -> StableConfederalDataValue
       (operator (FixedPoint tag operator))
       object
unrollFixedPointValue (FixedPointValue value) = value

-- | Observe one layer without exposing the value constructor.
withFixedPointValue
  :: FixedPointValue tag operator object
  -> (StableConfederalDataValue
        (operator (FixedPoint tag operator))
        object
      -> result)
  -> result
withFixedPointValue value useValue =
  useValue (unrollFixedPointValue value)

-- | Tie the guarded fixed-point knot for an operator interpreter.
fixedPoint
  :: (StableConfederalData (FixedPoint tag operator)
      -> StableConfederalData
           (operator (FixedPoint tag operator)))
  -> StableConfederalData (FixedPoint tag operator)
fixedPoint interpret = recursive
  where
    layer = interpret recursive

    recursive =
      stableConfederalData
        (\arrow value ->
          rollFixedPointValue
            (mapStableConfederalData
              layer arrow (unrollFixedPointValue value)))
        (stableConfederalDataIdentity layer . unrollFixedPointValue)
        (\second first value ->
          stableConfederalDataComposition
            layer second first (unrollFixedPointValue value))

-- | Expose the single operator layer generated by a fixed point.
fixedPointLayer
  :: (StableConfederalData (FixedPoint tag operator)
      -> StableConfederalData
           (operator (FixedPoint tag operator)))
  -> StableConfederalData (operator (FixedPoint tag operator))
fixedPointLayer interpret = interpret (fixedPoint interpret)

-- | Roll one operator layer into its fixed point.
rollFixedPoint
  :: (StableConfederalData (FixedPoint tag operator)
      -> StableConfederalData
           (operator (FixedPoint tag operator)))
  -> StableConfederalDataHom
       (operator (FixedPoint tag operator))
       (FixedPoint tag operator)
rollFixedPoint interpret =
  stableConfederalDataHom
    (fixedPointLayer interpret)
    (fixedPoint interpret)
    rollFixedPointValue
    (\_ _ -> ())

-- | Unroll a fixed point into one operator layer.
unrollFixedPoint
  :: (StableConfederalData (FixedPoint tag operator)
      -> StableConfederalData
           (operator (FixedPoint tag operator)))
  -> StableConfederalDataHom
       (FixedPoint tag operator)
       (operator (FixedPoint tag operator))
unrollFixedPoint interpret =
  stableConfederalDataHom
    (fixedPoint interpret)
    (fixedPointLayer interpret)
    unrollFixedPointValue
    (\_ _ -> ())
