cabal-version:      3.0
name:               datra
version:            0.1.0.0
synopsis:           Root package for the Datra project
license:            BSD-3-Clause
license-file:       datra-haskell/LICENSE
build-type:         Simple

library
    exposed-modules:  Datra
    hs-source-dirs:   haskell-src
    build-depends:    base >= 4.14 && < 5
    default-language: GHC2021
    ghc-options:      -Wall

executable datra
    main-is:          Main.hs
    hs-source-dirs:   haskell-app
    build-depends:
        base >= 4.14 && < 5,
        datra-haskell
    default-language: GHC2021
    ghc-options:      -Wall
