-- | Public folio API backed by the hidden implementation.
module Folio
  ( Folio
  , PageOrder
  , folio
  , singletonFolio
  , appendPage
  , folioLength
  , originChain
  , originValue
  , originUnique
  , folioMapIdentity
  , folioMapComposition
  , lastChain
  , paddedIndex
  , pageOrder
  , pageOrderSource
  , pageOrderTarget
  , withPageAt
  , withFolioMap
  ) where

import Folio.Internal
  ( Folio
  , PageOrder
  , appendPage
  , folio
  , folioLength
  , folioMapComposition
  , folioMapIdentity
  , lastChain
  , originChain
  , originUnique
  , originValue
  , pageOrder
  , pageOrderSource
  , pageOrderTarget
  , paddedIndex
  , singletonFolio
  , withFolioMap
  , withPageAt
  )
