cabal-version:      3.0
name:               datra-haskell
version:            0.1.0.0
synopsis:           A new Haskell project
description:
    A parser, interpreter, type system, and command-line implementation of the
    Datra language.
license:            Apache-2.0
license-file:       LICENSE
author:             qualiascript
maintainer:         qualiascript
copyright:          2026 qualiascript
homepage:           https://github.com/qualiascript/datra
bug-reports:        https://github.com/qualiascript/datra/issues
category:           Development
build-type:         Simple
tested-with:        GHC == 9.14.1
extra-doc-files:
    CHANGELOG.md
    README.md
    NOTICE
extra-source-files:
    std_lib.datra
    test/fixtures/cli/*.ast
    test/fixtures/cli/*.datra
    test/fixtures/cli/*.out
    test/fixtures/integration/*.datra
    test/fixtures/modules/*.datra
    src/DatraCore/LiquidPlugin.h

common warnings
    ghc-options: -Wall

common test-dependencies
    build-depends:
        hedgehog >= 1.4 && < 1.8,
        tasty >= 1.5 && < 1.6,
        tasty-hedgehog >= 1.4 && < 1.5,
        tasty-hunit >= 0.10 && < 0.11

flag liquid
    description: Enable LiquidHaskell verification during ordinary builds
    default:     True
    manual:      True

library
    import:           warnings
    exposed-modules:
        DatraLanguage.AST
        DatraLanguage.AST.Source
        DatraLanguage.AST.Operator
        DatraLanguage.AST.Reserved
        DatraLanguage.AST.Reserved.Bootstrap
        DatraLanguage.AST.Syntax
        DatraLanguage.Identifier
        DatraTypes
        AsciiMap
        AsciiString
        MapOperators
        MapOperators.AccessOperator
        MapOperators.IndexedAtlasMap
        MapOperators.OrderedAtlasMap
        MapOperators.ConcatOperator
        MapOperators.ExpansionOperator
        MapOperators.SequentialOperator
        NumericalOperators
        NumericalOperators.AdditionOperator
        NumericalOperators.ExponentiationOperator
        NumericalOperators.MultiplicationOperator
        NumericalOperators.NumericalOperand
        NumericalOperators.Range
        Dominion
        Dot
        SuperEllipsis
        SuperEllipsisInsertion
        SuperEllipsisRange
        SuperEllipsisValue
        Ellipsis
        EllipsisInsertion
        EllipsisRange
        EllipsisNatural
        EllipsisInteger
        BooleanType
        NaturalRange
        ValuedNaturalRange
        NaturalType
        IntegerRange
        ValuedIntegerRange
        IntegerType
        IdentifierValueType
        DependentIdentifierType
        SimpleIdentifierType
        AtlasMapFederation
        AtlasMapFederationExpression
        AtlasMapSubfederation
        TotalAtlasMap
        SpecificationOperator
        DatraLanguage.Diagnostics
        DatraLanguage.Diagnostics.Application
        DatraLanguage.Diagnostics.Interpreter
        DatraLanguage.Diagnostics.Locales.English
        DatraLanguage.Diagnostics.Locales.Romanian
        DatraLanguage.Diagnostics.Localization
        FixedPoint
        DomanialInsertion
        DatraOrdinal
        Chain
        Consolidation
        Folio
        PageElements
        Pagination
        Atlas
        AtlasExtent
        AtlasTerritory
        EmptyAtlas
        AtlasMerge
        AtlasSequence
        AtlasConfederation
        AtlasFederation
        AtlasHorizontalSum
        AtlasCoveredPageElement
        AtlasMap
        AtlasTransposal
        OrderedAtlasTransposal
        ChainedDominionAtlas
        RankedDominionAtlas
        AtlasTransversal
        AtlasTransversalMap
        Charter
        Coalition
        DomanialInclusion
        StableAtlasTransversal
        DataTransformation
        DataTransversal
        StableDataTransversal
        StableConfederalData
        HorizontalSum
        HorizontalSum.Syntax
        StableConfederalDataMonoidal
        StableConfederalDataKleisli
        StableConfederalDataKleisli.Syntax
        Navigation
        Expedition
        DataTransformationMap
    other-modules:
        PageElements.Internal
        PageElements.LiquidInternal
        Pagination.Internal
        Pagination.LiquidInternal
        Atlas.Internal
        Atlas.LiquidInternal
        AtlasExtent.Internal
        AtlasTerritory.Internal
        EmptyAtlas.Internal
        AtlasMerge.Internal
        AtlasConfederation.Internal
        AtlasFederation.Internal
        AtlasMapFederation.Internal
        AtlasHorizontalSum.Internal
        Atlas.Morphism.Internal
        Atlas.Morphism.LiquidInternal
        AtlasCoveredPageElement.Internal
        AtlasMap.Internal
        TotalAtlasMap.Internal
        AtlasTransposal.Internal
        OrderedAtlasTransposal.Internal
        AtlasTransversal.Internal
        AtlasTransversalMap.Internal
        Charter.Internal
        Charter.LiquidInternal
        Coalition.Internal
        DomanialInclusion.Internal
        DomanialInclusion.LiquidInternal
        StableAtlasTransversal.Internal
        DataTransformation.Internal
        DataTransformation.LiquidInternal
        DataTransversal.Internal
        StableDataTransversal.Internal
        StableConfederalData.Internal
        HorizontalSum.Internal
        StableConfederalDataMonoidal.Internal
        StableConfederalDataKleisli.Internal
        Navigation.Internal
        Expedition.Internal
        DataTransformationMap.Internal
        Chain.Internal
        Chain.LiquidInternal
        Consolidation.Internal
        Consolidation.LiquidInternal
        DatraOrdinal.Internal
        DatraOrdinal.LiquidInternal
        DomanialInsertion.Internal
        DomanialInsertion.LiquidInternal
        Dominion.Internal
        Folio.Internal
        Folio.LiquidInternal
        NumericalOperators.Internal
        NumericalOperators.Semantics
        MapOperators.Internal
        NaturalRange.Interval
        IntegerRange.Interval
        IntegerRange.Encoding
        OrdinalSequence
        SuperEllipsisRange.Description
        Evaluation.Access
        Evaluation.Access.Composition
        Evaluation.Access.Federation
        Evaluation.Access.Identifier
        Evaluation.Access.RangeSelection
        Evaluation.Access.Specification
        Evaluation.Construction
        Evaluation.Boolean
        Evaluation.Either
        Evaluation.Error
        Evaluation.Federation
        Evaluation.Federation.Structure
        Evaluation.FunctionArguments
        Evaluation.Identifier
        Evaluation.Map
        Evaluation.Numerical
        Evaluation.Optional
        Evaluation.Overload
        Evaluation.DatraType
        Evaluation.Range
        Evaluation.Specification
        Evaluation.Specification.ArgumentMap
        Evaluation.Specification.Composition
        Evaluation.Specification.Decision
        Evaluation.Specification.Federation
        Evaluation.Specification.String
        Evaluation.Specification.Subfederation
        Evaluation.ToString
        Evaluation.ToString.Injectivity
        Evaluation.TypeFamily.BuiltinMeta
        Evaluation.TypeFamily
        Evaluation.TypeFamily.Function
        Evaluation.TypeFamily.Structural
        Evaluation.TypeFamily.Structural.Specification
        Evaluation.TypeFamily.Structural.Subfederation
        Evaluation.TypeFamily.TotalBlock
        Evaluation.Value
        Evaluation.Value.Semantics
        Evaluation.Arguments
        Evaluation.Eval
        Extract
        DatraLanguage.Diagnostics.Locales.Rendering
    build-depends:
        base >= 4.14 && < 5,
        containers >= 0.6 && < 0.9,
        prettyprinter >= 1.7 && < 1.8
    if flag(liquid)
        build-depends:
            liquidhaskell == 0.9.14.1.1
    hs-source-dirs:
        src
        src/DatraCore/Atlases/Core
        src/DatraCore/Atlases/Core/Chain
        src/DatraCore/Atlases/Core/PageElements
        src/DatraCore/Atlases/Core/Pagination
        src/DatraCore/Atlases/Core/Atlas
        src/DatraCore/DataTransformations/DataTransformations
        src/DatraCore/DataTransformations/DataTransformations/DataTransformation
        src/DatraCore/DataTransformations/DataTransformations/DataTransversal
        src/DatraCore/DataTransformations/DataTransformations/StableDataTransversal
        src/DatraCore/DataTransformations/StableConfederalData
        src/DatraCore/DataTransformations/StableConfederalData/StableConfederalData
        src/DatraCore/DataTransformations/StableConfederalData/HorizontalSum
        src/DatraCore/DataTransformations/StableConfederalData/StableConfederalDataMonoidal
        src/DatraCore/DataTransformations/StableConfederalData/StableConfederalDataKleisli
        src/DatraCore/DataTransformations/DataTransformationMaps
        src/DatraCore/DataTransformations/DataTransformationMaps/Navigation
        src/DatraCore/DataTransformations/DataTransformationMaps/Expedition
        src/DatraCore/DataTransformations/DataTransformationMaps/DataTransformationMap
        src/DatraCore/DataTransformations/DataTransformationMaps/AtlasMapFederation
        src/DatraCore/Atlases/Core/Consolidation
        src/DatraCore/Atlases/Core/DatraOrdinal
        src/DatraCore/Atlases/Core/Dominion
        src/DatraCore/Atlases/Derived/AtlasDerived
        src/DatraCore/Atlases/Derived/AtlasDerived/AtlasExtent
        src/DatraCore/Atlases/Derived/AtlasDerived/AtlasTerritory
        src/DatraCore/Atlases/Derived/AtlasDerived/EmptyAtlas
        src/DatraCore/Atlases/Derived/AtlasDerived/AtlasCoveredPageElement
        src/DatraCore/Atlases/Derived/AtlasConfederations
        src/DatraCore/Atlases/Derived/AtlasConfederations/AtlasMerge
        src/DatraCore/Atlases/Derived/AtlasConfederations/AtlasSequence
        src/DatraCore/Atlases/Derived/AtlasConfederations/AtlasConfederation
        src/DatraCore/Atlases/Derived/AtlasConfederations/AtlasFederation
        src/DatraCore/Atlases/Derived/AtlasConfederations/AtlasHorizontalSum
        src/DatraCore/Atlases/Derived/Cartography
        src/DatraCore/Atlases/Derived/Cartography/AtlasMap
        src/DatraCore/Atlases/Derived/Cartography/TotalAtlasMap
        src/DatraCore/Atlases/Derived/Cartography/AtlasTransversalMap
        src/DatraCore/Atlases/Derived/Cartography/Charter
        src/DatraCore/Atlases/Derived/Coalitions
        src/DatraCore/Atlases/Derived/Coalitions/Coalition
        src/DatraCore/Atlases/Derived/Coalitions/DomanialInclusion
        src/DatraTypes
        src/DatraTypes/Strings
        src/DatraTypes/Ellipses
        src/DatraTypes/NaturalRanges
        src/DatraTypes/IntegerRanges
        src/DatraTypes/Booleans
        src/DatraTypes/Identifiers
        src/DatraTypes/AtlasMapFederations
        src/DatraCore/Atlases/Derived/AtlasTransposals
        src/DatraCore/Atlases/Derived/AtlasTransposals/AtlasTransposal
        src/DatraCore/Atlases/Derived/AtlasTransposals/OrderedAtlasTransposal
        src/DatraCore/Atlases/Derived/AtlasTransposals/AtlasTransversal
        src/DatraCore/Atlases/Derived/AtlasTransposals/StableAtlasTransversal
        src/DatraCore/Atlases/Core/DomanialInsertion
        src/DatraCore/Atlases/Core/Folio
    default-language: GHC2021

executable datra-haskell
    import:           warnings
    main-is:          Main.hs
    other-modules:
        Interpreting
        RuntimeModules
        ModuleNames
        ModuleLoading
        FunctionInference
        StdLib
        SyntaxDefinitions
        Parsing
        Rendering
    build-depends:
        base >= 4.14 && < 5,
        datra-haskell,
        filepath >= 1.4 && < 1.6,
        directory >= 1.3 && < 1.4,
        megaparsec >= 9.8 && < 10,
        template-haskell < 2.25,
        optparse-applicative >= 0.18 && < 0.20,
        parser-combinators >= 1.3 && < 2,
        prettyprinter >= 1.7 && < 1.8,
        text >= 2.0 && < 2.2,
        transformers >= 0.5 && < 0.7
    hs-source-dirs:   app
    default-language: GHC2021

test-suite datra-core-test
    import:           warnings, test-dependencies
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          DatraCoreTests.hs
    build-depends:
        base >= 4.14 && < 5,
        datra-haskell

test-suite datra-types-test
    import:           warnings, test-dependencies
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          DatraTypesTests.hs
    build-depends:
        base >= 4.14 && < 5,
        containers >= 0.6 && < 0.9,
        datra-haskell

test-suite datra-parsing-test
    import:           warnings, test-dependencies
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    hs-source-dirs:
        test
        app
    main-is:          DatraParsingTests.hs
    other-modules:
        Parsing
        StdLib
        SyntaxDefinitions
        ModuleNames
    ghc-options:      -main-is DatraParsingTests.main
    build-depends:
        template-haskell,
        filepath,
        base >= 4.14 && < 5,
        datra-haskell,
        megaparsec >= 9.8 && < 10,
        parser-combinators >= 1.3 && < 2,
        text >= 2.0 && < 2.2,
        transformers >= 0.5 && < 0.7

test-suite datra-interpreting-test
    import:           warnings, test-dependencies
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    hs-source-dirs:
        test
        app
    main-is:          DatraInterpretingTests.hs
    other-modules:
        Datra.Interpreter.DatraTypeLawTests
        Datra.Interpreter.FunctionTests
        Datra.Interpreter.IntegrationTests
        Datra.Interpreter.ModuleTests
        Datra.Interpreter.OverloadAssertionTests
        Datra.Interpreter.ScopeTests
        Datra.Interpreter.StandardLibraryTests
        Datra.TestSupport
        Interpreting
        RuntimeModules
        ModuleNames
        ModuleLoading
        FunctionInference
        StdLib
        SyntaxDefinitions
        Parsing
        Rendering
    ghc-options:      -main-is DatraInterpretingTests.main
    build-depends:
        filepath,
        directory,
        template-haskell,
        base >= 4.14 && < 5,
        datra-haskell,
        megaparsec >= 9.8 && < 10,
        parser-combinators >= 1.3 && < 2,
        prettyprinter >= 1.7 && < 1.8,
        text >= 2.0 && < 2.2,
        transformers >= 0.5 && < 0.7

test-suite datra-cli-test
    import:           warnings, test-dependencies
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          DatraCliTests.hs
    build-tool-depends:
        datra-haskell:datra-haskell
    build-depends:
        base >= 4.14 && < 5,
        datra-haskell,
        directory >= 1.3 && < 1.4,
        process >= 1.6 && < 1.7,
        tasty >= 1.5 && < 1.6,
        tasty-hunit >= 0.10 && < 0.11
