cabal-version:      3.0
name:               datra-haskell
version:            0.1.0.0
synopsis:           A new Haskell project
license:            Apache-2.0
license-file:       LICENSE
author:             qualiascript
copyright:          2026 qualiascript
homepage:           https://github.com/qualiascript/datra
bug-reports:        https://github.com/qualiascript/datra/issues
category:           Development
build-type:         Simple
tested-with:        GHC == 9.14.1
extra-doc-files:
    CHANGELOG.md
    README.md
    NOTICE
extra-source-files:
    src/DatraCore/LiquidPlugin.h

common warnings
    ghc-options: -Wall

flag liquid
    description: Enable LiquidHaskell verification during ordinary builds
    default:     True
    manual:      True

library
    import:           warnings
    exposed-modules:
        AsciiDominion
        MapMakingOperators
        MapMakingOperators.ConcatOperator
        MapMakingOperators.ConcatOperator.Syntax
        MapMakingOperators.ExpansionOperator
        MapMakingOperators.ExpansionOperator.Syntax
        MapMakingOperators.SequentialOperator
        MapMakingOperators.SequentialOperator.Syntax
        CanonicalCharsDominion
        Dominion
        Ellipsis
        EllipsisInsertion
        EllipsisNatural
        EllipsisNaturalRange
        FiniteDominion
        DomanialInsertion
        DatraOrdinal
        Chain
        Consolidation
        Folio
        PageElements
        Pagination
        Atlas
        AtlasExtent
        AtlasTerritory
        EmptyAtlas
        AtlasMerge
        AtlasSequence
        AtlasConfederation
        AtlasFederation
        AtlasHorizontalSum
        AtlasCoveredPageElement
        AtlasMap
        AtlasTransposal
        OrderedAtlasTransposal
        AtlasTransversal
        AtlasTransversalMap
        Charter
        Coalition
        DomanialInclusion
        StableAtlasTransversal
        DataTransformation
        DataTransposal
        OrderedDataTransposal
        DataTransversal
        StableDataTransversal
        StableConfederalData
        HorizontalSum
        HorizontalSum.Syntax
        StableConfederalDataMonoidal
        StableConfederalDataKleisli
        StableConfederalDataKleisli.Syntax
        Navigation
        Expedition
        DataTransformationMap
    other-modules:
        PageElements.Internal
        PageElements.LiquidInternal
        Pagination.Internal
        Pagination.LiquidInternal
        Atlas.Internal
        Atlas.LiquidInternal
        AtlasExtent.Internal
        AtlasTerritory.Internal
        EmptyAtlas.Internal
        AtlasMerge.Internal
        AtlasConfederation.Internal
        AtlasFederation.Internal
        AtlasHorizontalSum.Internal
        Atlas.Morphism.Internal
        Atlas.Morphism.LiquidInternal
        AtlasCoveredPageElement.Internal
        AtlasMap.Internal
        AtlasTransposal.Internal
        OrderedAtlasTransposal.Internal
        AtlasTransversal.Internal
        AtlasTransversalMap.Internal
        Charter.Internal
        Charter.LiquidInternal
        Coalition.Internal
        DomanialInclusion.Internal
        DomanialInclusion.LiquidInternal
        StableAtlasTransversal.Internal
        DataTransformation.Internal
        DataTransformation.LiquidInternal
        DataTransposal.Internal
        OrderedDataTransposal.Internal
        DataTransversal.Internal
        StableDataTransversal.Internal
        StableConfederalData.Internal
        HorizontalSum.Internal
        StableConfederalDataMonoidal.Internal
        StableConfederalDataKleisli.Internal
        Navigation.Internal
        Expedition.Internal
        DataTransformationMap.Internal
        Chain.Internal
        Chain.LiquidInternal
        Consolidation.Internal
        Consolidation.LiquidInternal
        DatraOrdinal.Internal
        DatraOrdinal.LiquidInternal
        DomanialInsertion.Internal
        DomanialInsertion.LiquidInternal
        Dominion.Internal
        Folio.Internal
        Folio.LiquidInternal
    build-depends:
        base >= 4.14 && < 5,
        containers >= 0.6 && < 0.9
    if flag(liquid)
        build-depends:
            liquidhaskell == 0.9.14.1.1
    hs-source-dirs:
        src/DatraCore/Atlases/Core
        src/DatraCore/Atlases/Core/Chain
        src/DatraCore/Atlases/Core/PageElements
        src/DatraCore/Atlases/Core/Pagination
        src/DatraCore/Atlases/Core/Atlas
        src/DatraCore/DataTransformations/DataTransformations
        src/DatraCore/DataTransformations/DataTransformations/DataTransformation
        src/DatraCore/DataTransformations/DataTransformations/DataTransposal
        src/DatraCore/DataTransformations/DataTransformations/OrderedDataTransposal
        src/DatraCore/DataTransformations/DataTransformations/DataTransversal
        src/DatraCore/DataTransformations/DataTransformations/StableDataTransversal
        src/DatraCore/DataTransformations/StableConfederalData
        src/DatraCore/DataTransformations/StableConfederalData/StableConfederalData
        src/DatraCore/DataTransformations/StableConfederalData/HorizontalSum
        src/DatraCore/DataTransformations/StableConfederalData/StableConfederalDataMonoidal
        src/DatraCore/DataTransformations/StableConfederalData/StableConfederalDataKleisli
        src/DatraCore/DataTransformations/DataTransformationMaps
        src/DatraCore/DataTransformations/DataTransformationMaps/Navigation
        src/DatraCore/DataTransformations/DataTransformationMaps/Expedition
        src/DatraCore/DataTransformations/DataTransformationMaps/DataTransformationMap
        src/DatraCore/Atlases/Core/Consolidation
        src/DatraCore/Atlases/Core/DatraOrdinal
        src/DatraCore/Atlases/Core/Dominion
        src/DatraCore/Atlases/Derived/AtlasDerived
        src/DatraCore/Atlases/Derived/AtlasDerived/AtlasExtent
        src/DatraCore/Atlases/Derived/AtlasDerived/AtlasTerritory
        src/DatraCore/Atlases/Derived/AtlasDerived/EmptyAtlas
        src/DatraCore/Atlases/Derived/AtlasDerived/AtlasCoveredPageElement
        src/DatraCore/Atlases/Derived/AtlasConfederations
        src/DatraCore/Atlases/Derived/AtlasConfederations/AtlasMerge
        src/DatraCore/Atlases/Derived/AtlasConfederations/AtlasSequence
        src/DatraCore/Atlases/Derived/AtlasConfederations/AtlasConfederation
        src/DatraCore/Atlases/Derived/AtlasConfederations/AtlasFederation
        src/DatraCore/Atlases/Derived/AtlasConfederations/AtlasHorizontalSum
        src/DatraCore/Atlases/Derived/Cartography
        src/DatraCore/Atlases/Derived/Cartography/AtlasMap
        src/DatraCore/Atlases/Derived/Cartography/AtlasTransversalMap
        src/DatraCore/Atlases/Derived/Cartography/Charter
        src/DatraCore/Atlases/Derived/Coalitions
        src/DatraCore/Atlases/Derived/Coalitions/Coalition
        src/DatraCore/Atlases/Derived/Coalitions/DomanialInclusion
        src/DatraTypes
        src/DatraTypes/CharacterDominions
        src/DatraTypes/Ellipses
        src/DatraCore/Atlases/Derived/AtlasTransposals
        src/DatraCore/Atlases/Derived/AtlasTransposals/AtlasTransposal
        src/DatraCore/Atlases/Derived/AtlasTransposals/OrderedAtlasTransposal
        src/DatraCore/Atlases/Derived/AtlasTransposals/AtlasTransversal
        src/DatraCore/Atlases/Derived/AtlasTransposals/StableAtlasTransversal
        src/DatraCore/Atlases/Core/DomanialInsertion
        src/DatraCore/Atlases/Core/Folio
    default-language: GHC2021

executable datra-haskell
    import:           warnings
    main-is:          Main.hs
    build-depends:
        base >= 4.14 && < 5,
        datra-haskell
    hs-source-dirs:   app
    default-language: GHC2021

test-suite datra-core-test
    import:           warnings
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          DatraCoreTests.hs
    build-depends:
        base >= 4.14 && < 5,
        datra-haskell

test-suite datra-types-test
    import:           warnings
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          DatraTypesTests.hs
    build-depends:
        base >= 4.14 && < 5,
        containers >= 0.6 && < 0.9,
        datra-haskell
