cabal-version:      3.0
name:               datra-haskell
version:            0.1.0.0
synopsis:           A new Haskell project
license:            Apache-2.0
license-file:       LICENSE
author:             qualiascript
copyright:          2026 qualiascript
homepage:           https://github.com/qualiascript/datra
bug-reports:        https://github.com/qualiascript/datra/issues
category:           Development
build-type:         Simple
extra-doc-files:
    CHANGELOG.md
    README.md
    NOTICE

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:
        Dominion
        FiniteDominion
        DomanialInsertion
        DatraOrdinal
        Chains
        Consolidation
    other-modules:
        Chains.Internal
        Consolidation.Internal
        Consolidation.LiquidInternal
        DatraOrdinal.Internal
        DomanialInsertion.Internal
        DomanialInsertion.LiquidInternal
        Dominion.Internal
        FiniteDominion.Internal
    build-depends:
        base >= 4.14 && < 5,
        containers >= 0.6 && < 0.9,
        liquidhaskell == 0.9.4.7.0
    hs-source-dirs:
        src/DatraCore
        src/DatraCore/Chains
        src/DatraCore/Consolidation
        src/DatraCore/DatraOrdinal
        src/DatraCore/Dominion
        src/DatraCore/FiniteDominion
        src/DatraCore/DomanialInsertion
    default-language: GHC2021

executable datra-haskell
    import:           warnings
    main-is:          Main.hs
    build-depends:
        base >= 4.14 && < 5,
        datra-haskell
    hs-source-dirs:   app
    default-language: GHC2021

test-suite datra-haskell-test
    import:           warnings
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
        base >= 4.14 && < 5,
        containers >= 0.6 && < 0.9,
        datra-haskell
