-- | Atlases and their morphisms, built over finite paginations with an
-- explicitly stable infinite padded spine.
--
-- Atlas object and primitive-morphism laws are checked by LiquidHaskell.
module Atlas
  ( Atlas
  , AtlasDataAction
  , AtlasMorphism
  , AtlasMorphismAction
  , AtlasObjectMap
  , AtlasMappedObject
  , IdentityAtlasObjectMap
  , AtlasMorphismImage
  , AtlasCategory
  , AtlasObject
  , AtlasObjectAtlasScope
  , AtlasObjectPaginationScope
  , AtlasObjectCellData
  , AtlasWitness
  , AtlasHom
  , atlasDataAction
  , atlas
  , atlasPagination
  , atlasFolio
  , atlasPageElements
  , atlasCardinality
  , normalizeAtlasElement
  , normalizeAtlasArrow
  , atlasCoherence
  , atlasDataAt
  , mapAtlasData
  , atlasDataCoherence
  , normalizeAtlasDatum
  , atlasMorphismAction
  , identityAtlasObjectMap
  , atlasObjectMap
  , withAtlasMorphismImage
  , atlasMorphism
  , atlasMorphismPagination
  , mapAtlasMorphismElement
  , mapAtlasMorphismArrow
  , mapAtlasMorphismData
  , identityAtlasMorphism
  , composeAtlasMorphisms
  , atlasCategory
  , atlasCategoryIdentity
  , atlasCategoryCompose
  , atlasWitness
  , atlasHom
  , materializeAtlasHom
  , atlasHomPagination
  , mapAtlasHomElement
  , mapAtlasHomArrow
  , mapAtlasHomData
  ) where

import Atlas.Internal
  ( Atlas
  , AtlasDataAction
  , atlas
  , atlasDataAction
  , atlasCardinality
  , atlasCoherence
  , atlasDataAt
  , atlasDataCoherence
  , atlasFolio
  , atlasPageElements
  , atlasPagination
  , mapAtlasData
  , normalizeAtlasArrow
  , normalizeAtlasDatum
  , normalizeAtlasElement
  )
import Atlas.Morphism.Internal
  ( AtlasMorphism
  , AtlasMorphismAction
  , AtlasObjectMap
  , AtlasMappedObject
  , IdentityAtlasObjectMap
  , AtlasMorphismImage
  , AtlasCategory
  , AtlasObject
  , AtlasObjectAtlasScope
  , AtlasObjectPaginationScope
  , AtlasObjectCellData
  , AtlasWitness
  , AtlasHom
  , atlasMorphism
  , atlasMorphismAction
  , identityAtlasObjectMap
  , atlasObjectMap
  , atlasMorphismPagination
  , atlasCategory
  , atlasCategoryCompose
  , atlasCategoryIdentity
  , atlasWitness
  , atlasHom
  , materializeAtlasHom
  , atlasHomPagination
  , mapAtlasHomElement
  , mapAtlasHomArrow
  , mapAtlasHomData
  , composeAtlasMorphisms
  , identityAtlasMorphism
  , mapAtlasMorphismArrow
  , mapAtlasMorphismData
  , mapAtlasMorphismElement
  , withAtlasMorphismImage
  )
