-- | Public consolidation and carrier-transport API backed by the hidden
-- implementation.
module Consolidation
  ( Consolidation
  , applyConsolidation
  , consolidationPreimage
  , consolidationMonotone
  , consolidationPointSurjective
  , consolidation
  , identityConsolidation
  , composeConsolidations
  , sumConsolidations
  , Coconsolidation
  , composeCoconsolidations
  , op
  , unop
  , ConsolidationTransport
  , runConsolidationTransport
  , consolidationTransport
  , consolidationTransportIdentity
  , consolidationTransportComposition
  , transportCoconsolidation
  ) where

import Consolidation.Internal
  ( Coconsolidation
  , Consolidation
  , ConsolidationTransport
  , applyConsolidation
  , composeConsolidations
  , composeCoconsolidations
  , consolidation
  , consolidationMonotone
  , consolidationPointSurjective
  , consolidationPreimage
  , identityConsolidation
  , op
  , runConsolidationTransport
  , consolidationTransport
  , consolidationTransportComposition
  , consolidationTransportIdentity
  , sumConsolidations
  , transportCoconsolidation
  , unop
  )
