-- | The category of cell occurrences of a folio.
module PageElements
  ( PageElements
  , PageElement
  , SomePageElement
  , PageElementArrow
  , pageElements
  , pageElement
  , pageElementPage
  , pageElementPosition
  , withPageElement
  , withPageElementValue
  , pageElementArrow
  , arrowSource
  , arrowTarget
  , identityPageElementArrow
  , composePageElementArrows
  , pageElementArrowEndpoints
  , pageElementArrowThin
  , pageElementArrowLeftIdentity
  , pageElementArrowRightIdentity
  , pageElementArrowAssociativity
  ) where

import PageElements.Internal
  ( PageElement
  , PageElementArrow
  , PageElements
  , SomePageElement
  , arrowSource
  , arrowTarget
  , pageElement
  , pageElementArrow
  , pageElements
  , composePageElementArrows
  , identityPageElementArrow
  , pageElementArrowAssociativity
  , pageElementArrowEndpoints
  , pageElementArrowLeftIdentity
  , pageElementArrowRightIdentity
  , pageElementArrowThin
  , pageElementPage
  , pageElementPosition
  , withPageElement
  , withPageElementValue
  )
