-- | The category of cell occurrences of a folio.
module PageElements
  ( PageElements
  , PageElementIndex
  , PageElement
  , SomePageElement
  , PageElementArrow
  , pageElements
  , pageElementIndex
  , pageElementIndexPage
  , pageElementIndexPosition
  , pageElement
  , pageElementPage
  , pageElementPosition
  , withPageElement
  , withPageElementValue
  , somePageElementPrecedes
  , somePageElementTransported
  , somePageElementTransportedReflexive
  , pageElementArrow
  , pageElementTransported
  , arrowSource
  , arrowTarget
  , identityPageElementArrow
  , composePageElementArrows
  , pageElementArrowEndpoints
  , pageElementArrowThin
  , pageElementArrowLeftIdentity
  , pageElementArrowRightIdentity
  , pageElementArrowAssociativity
  ) where

import PageElements.Internal
  ( PageElement
  , PageElementIndex
  , PageElementArrow
  , PageElements
  , SomePageElement
  , arrowSource
  , arrowTarget
  , pageElement
  , pageElementIndex
  , pageElementIndexPage
  , pageElementIndexPosition
  , pageElementArrow
  , pageElements
  , composePageElementArrows
  , identityPageElementArrow
  , pageElementArrowAssociativity
  , pageElementArrowEndpoints
  , pageElementArrowLeftIdentity
  , pageElementArrowRightIdentity
  , pageElementArrowThin
  , pageElementTransported
  , pageElementPage
  , pageElementPosition
  , withPageElement
  , withPageElementValue
  , somePageElementPrecedes
  , somePageElementTransported
  , somePageElementTransportedReflexive
  )
