-- | Public chain API backed by the hidden chain implementation.
module Chain
  ( Chain
  , ChainIndex
  , chainOrdinalLT
  , positionMatches
  , chainOrderType
  , chainPosition
  , chainIndex
  , chainIndexOf
  , chainIndexOrderType
  , chainIndexPosition
  , chainObjectAt
  , chainPositionBelow
  , chainPositionInjective
  , chainPositionSurjective
  , chain
  , compareInChain
  , hasArrow
  , sumChains
  , spine
  ) where

import Chain.Internal
  ( Chain
  , ChainIndex
  , chain
  , chainIndex
  , chainIndexOf
  , chainIndexOrderType
  , chainIndexPosition
  , chainObjectAt
  , chainOrderType
  , chainOrdinalLT
  , chainPosition
  , chainPositionBelow
  , chainPositionInjective
  , chainPositionSurjective
  , compareInChain
  , hasArrow
  , positionMatches
  , spine
  , sumChains
  )
